; Listing generated by Microsoft (R) Optimizing Compiler Version 19.26.28806.0 

	TITLE	D:\Programming\GameHacking\Assembly\Creel\CppAsAssembly\CppAsAssembly\CppAsAssembly.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__68CC8892_vcruntime_new@h DB 01H
__741AE07E_corecrt_math@h DB 01H
__B49664B7_stdlib@h DB 01H
__B0B2AE59_cstdlib DB 01H
__0CE2504A_cmath DB 01H
__A2143F22_corecrt_stdio_config@h DB 01H
__829E1958_corecrt_wstdio@h DB 01H
__6DFAE8B8_stdio@h DB 01H
__1FEB9909_corecrt_memcpy_s@h DB 01H
__A751F051_corecrt_memory@h DB 01H
__9200769A_corecrt_wstring@h DB 01H
__32E5F013_string@h DB 01H
__C6E16F6F_corecrt_wconio@h DB 01H
__6D390390_corecrt_wio@h DB 01H
__1157D6BA_corecrt_wtime@h DB 01H
__1DC1E279_stat@h DB 01H
__93DC0B45_wchar@h DB 01H
__79389A52_type_traits DB 01H
__9DD7FB47_xutility DB 01H
__20BB4341_malloc@h DB 01H
__E60FAE9C_vcruntime_exception@h DB 01H
__5E1BED6E_exception DB 01H
__E380AC8B_limits DB 01H
__ED2A4811_xmemory DB 01H
__99F9CE8D_xstring DB 01H
__D755D733_stdexcept DB 01H
__6D45D93D_xcall_once@h DB 01H
__D218CB1D_system_error DB 01H
__78FD32FC_vcruntime_typeinfo@h DB 01H
__ED08085E_typeinfo DB 01H
__5F2EA005_memory DB 01H
__736BF70A_xfacet DB 01H
__B2D2BA86_ctype@h DB 01H
__F281EB96_xlocinfo DB 01H
__46C7BABC_xlocale DB 01H
__CB649C85_xiosbase DB 01H
__D840DCAB_xlocnum DB 01H
__593D1C9E_ios DB 01H
__EC420DC6_CppAsAssembly@cpp DB 01H
__36075542_istream DB 01H
__55D76078_ostream DB 01H
__D5F56F8F_streambuf DB 01H
__8C7B4C07_iterator DB 01H
__2F69790D_iosfwd DB 01H
__87BF2BD2_utility DB 01H
__70A0BCC0_xstddef DB 01H
__541761B8_xatomic@h DB 01H
msvcjmc	ENDS
PUBLIC	?__empty_global_delete@@YAXPAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPAXI@Z		; __empty_global_delete
PUBLIC	?WhereVarStored@@YAHHHHHH@Z			; WhereVarStored
PUBLIC	_main
PUBLIC	__JustMyCode_Default
EXTRN	__imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z:PROC
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A:BYTE
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File D:\Programming\GameHacking\Assembly\Creel\CppAsAssembly\CppAsAssembly\CppAsAssembly.cpp
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT

; 7    : int main() {

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __EC420DC6_CppAsAssembly@cpp
	call	@__CheckForDebuggerJustMyCode@4

; 8    : 	std::cout << WhereVarStored(5, 6, 7, 8, 9);

	push	9
	push	8
	push	7
	push	6
	push	5
	call	?WhereVarStored@@YAHHHHHH@Z		; WhereVarStored
	add	esp, 20					; 00000014H
	mov	esi, esp
	push	eax
	mov	ecx, DWORD PTR __imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A
	call	DWORD PTR __imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@H@Z
	cmp	esi, esp
	call	__RTC_CheckEsp

; 9    : }

	xor	eax, eax
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File D:\Programming\GameHacking\Assembly\Creel\CppAsAssembly\CppAsAssembly\CppAsAssembly.cpp
;	COMDAT ?WhereVarStored@@YAHHHHHH@Z
_TEXT	SEGMENT
_one$ = 8						; size = 4
_two$ = 12						; size = 4
_three$ = 16						; size = 4
_four$ = 20						; size = 4
_five$ = 24						; size = 4
?WhereVarStored@@YAHHHHHH@Z PROC			; WhereVarStored, COMDAT

; 3    : int WhereVarStored(int one, int two, int three, int four, int five) {

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __EC420DC6_CppAsAssembly@cpp
	call	@__CheckForDebuggerJustMyCode@4

; 4    : 	return one;

	mov	eax, DWORD PTR _one$[ebp]

; 5    : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?WhereVarStored@@YAHHHHHH@Z ENDP			; WhereVarStored
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File D:\Programming\GameHacking\Assembly\Creel\CppAsAssembly\CppAsAssembly\CppAsAssembly.cpp
;	COMDAT ?__empty_global_delete@@YAXPAXI@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
___formal$ = 12						; size = 4
?__empty_global_delete@@YAXPAXI@Z PROC			; __empty_global_delete, COMDAT

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __EC420DC6_CppAsAssembly@cpp
	call	@__CheckForDebuggerJustMyCode@4
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAXI@Z ENDP			; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File D:\Programming\GameHacking\Assembly\Creel\CppAsAssembly\CppAsAssembly\CppAsAssembly.cpp
;	COMDAT ?__empty_global_delete@@YAXPAX@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
?__empty_global_delete@@YAXPAX@Z PROC			; __empty_global_delete, COMDAT

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __EC420DC6_CppAsAssembly@cpp
	call	@__CheckForDebuggerJustMyCode@4
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
