; Listing generated by Microsoft (R) Optimizing Compiler Version 19.26.28806.0 

	TITLE	d:\programming\gamehacking\assembly\creel\cppasassembly\cppasassembly\cppasassembly.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

EXTRN	@__security_check_cookie@4:PROC
PUBLIC	_main
PUBLIC	?WhereVarStored@@YAHHHHHH@Z			; WhereVarStored
END
